### ISSUE TITLE
[question] Logs of the messages that might be lost.

### ISSUE THREAD

**Issue by k-kawa** [mia-0032/fluent-plugin-gcloud-pubsub-custom#20]
I have a question about the code around here.

https://github.com/mia-0032/fluent-plugin-gcloud-pubsub-custom/blob/master/lib/fluent/plugin/in_gcloud_pubsub.rb#L173

When `router.emit_stream` fails, the batch of messages looks like getting lost. Do you think it's helpful if this plug in writes logs about all the messages in such a case?

**Comment by mia-0032** [comment]
> When router.emit_stream fails, the batch of messages looks like getting lost.

Exactly... I think it is better skipping `acknowledge` when `router.emit_stream` fails.
I'll fix it later.
