### ISSUE TITLE
accept batches of messages?

### ISSUE THREAD

**Issue by studiotomi** [mia-0032/fluent-plugin-gcloud-pubsub-custom#33]
Can I post batch messages to this plugin?  I.e. instead of sending messages one at a time from my services, can I send them all in one payload to the plugin?

**Comment by mia-0032** [comment]
You can send messages to Fluentd by using input plugins. 

http://docs.fluentd.org/v0.12/articles/input-plugin-overview

I think it is easy way for your application to send them asynchronously that the application write messages to file and Fluentd read it by in_tail plugin.

http://docs.fluentd.org/v0.12/articles/in_tail

I do not know whether it meets the intention of your question.
If different, please reply again.

**Comment by mia-0032** [comment]
I'm going to close this issue. If you have more questions, please reopen it.
