### ISSUE TITLE
Not working with flunetd 0.12.35 and Ruby 2.3.0

### ISSUE THREAD

**Issue by mrunesson** [mia-0032/fluent-plugin-gcloud-pubsub-custom#36]
I try to run this plugin with fluentd-0.12.35 in docker container https://hub.docker.com/r/fluent/fluentd/ but get a protobuf error. This version number is for latest, but I have the same issue on edge image.
Which versions of fluentd and ruby is it tested with?
Do you have a workaround for this?

/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': Error relocating /home/fluent/.gem/ruby/2.3.0/gems/google-protobuf-3.3.0-x86_64-linux/lib/google/protobuf_c.so: __snprintf_chk: symbol not found - /home/fluent/.gem/ruby/2.3.0/gems/google-protobuf-3.3.0-x86_64-linux/lib/google/protobuf_c.so (LoadError)
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/fluent/.gem/ruby/2.3.0/gems/google-protobuf-3.3.0-x86_64-linux/lib/google/protobuf.rb:50:in `rescue in <top (required)>'
	from /home/fluent/.gem/ruby/2.3.0/gems/google-protobuf-3.3.0-x86_64-linux/lib/google/protobuf.rb:47:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/fluent/.gem/ruby/2.3.0/gems/grpc-google-iam-v1-0.6.8/lib/google/iam/v1/iam_policy_pb.rb:4:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/fluent/.gem/ruby/2.3.0/gems/google-cloud-pubsub-0.24.0/lib/google/cloud/pubsub/v1/publisher_client.rb:30:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/fluent/.gem/ruby/2.3.0/gems/google-cloud-pubsub-0.24.0/lib/google/cloud/pubsub/v1.rb:16:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/fluent/.gem/ruby/2.3.0/gems/google-cloud-pubsub-0.24.0/lib/google/cloud/pubsub/service.rb:19:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/fluent/.gem/ruby/2.3.0/gems/google-cloud-pubsub-0.24.0/lib/google/cloud/pubsub/project.rb:18:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/fluent/.gem/ruby/2.3.0/gems/google-cloud-pubsub-0.24.0/lib/google/cloud/pubsub.rb:17:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/fluent/.gem/ruby/2.3.0/gems/fluent-plugin-gcloud-pubsub-custom-0.4.5/lib/fluent/plugin/gcloud_pubsub/client.rb:1:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from /home/fluent/.gem/ruby/2.3.0/gems/fluent-plugin-gcloud-pubsub-custom-0.4.5/lib/fluent/plugin/out_gcloud_pubsub.rb:3:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.35/lib/fluent/plugin.rb:172:in `block in try_load_plugin'
	from /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.35/lib/fluent/plugin.rb:170:in `each'
	from /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.35/lib/fluent/plugin.rb:170:in `try_load_plugin'
	from /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.35/lib/fluent/plugin.rb:130:in `new_impl'
	from /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.35/lib/fluent/plugin.rb:59:in `new_output'
	from /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.35/lib/fluent/agent.rb:131:in `add_match'
	from /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.35/lib/fluent/agent.rb:64:in `block in configure'
	from /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.35/lib/fluent/agent.rb:57:in `each'
	from /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.35/lib/fluent/agent.rb:57:in `configure'
	from /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.35/lib/fluent/root_agent.rb:83:in `block in configure'
	from /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.35/lib/fluent/root_agent.rb:83:in `each'
	from /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.35/lib/fluent/root_agent.rb:83:in `configure'
	from /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.35/lib/fluent/engine.rb:129:in `configure'
	from /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.35/lib/fluent/engine.rb:103:in `run_configure'
	from /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.35/lib/fluent/supervisor.rb:489:in `run_configure'
	from /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.35/lib/fluent/supervisor.rb:160:in `block in start'
	from /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.35/lib/fluent/supervisor.rb:366:in `main_process'
	from /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.35/lib/fluent/supervisor.rb:339:in `block in supervise'
	from /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.35/lib/fluent/supervisor.rb:338:in `fork'
	from /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.35/lib/fluent/supervisor.rb:338:in `supervise'
	from /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.35/lib/fluent/supervisor.rb:156:in `start'
	from /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.35/lib/fluent/command/fluentd.rb:173:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.35/bin/fluentd:5:in `<top (required)>'
	from /usr/bin/fluentd:22:in `load'
	from /usr/bin/fluentd:22:in `<main>'

**Comment by mia-0032** [comment]
@mrunesson Thank you for your reporting.

Fluentd Docker image (version latest and edge) is based on Alpine. I think it cause the errors.
Does the same errors occur if you use Debian based image?

I run this plugin in my environment with Ruby 2.3.3 and below version of gems.

- fluent-plugin-gcloud-pubsub-custom (0.4.5)
- fluentd (0.12.31)
- google-cloud-pubsub (0.24.0)
- google-gax (0.8.1)
- google-protobuf (3.3.0 x86_64-linux)
- googleapis-common-protos (1.3.5)
- googleauth (0.5.1)
- grpc (1.2.0 x86_64-linux)
- grpc-google-iam-v1 (0.6.8)

**Comment by mrunesson** [comment]
@mia-0032 Thank you for your answer. I changed to use fluent/fluentd:debian and then it works.

**Comment by mia-0032** [comment]
You're welcome. I close this issue.
