### ISSUE TITLE
support tag placeholder for v0.14 

### ISSUE THREAD

**Issue by gyamxxx** [mia-0032/fluent-plugin-gcloud-pubsub-custom#42]
I want to use tag place holder for topic like that.
```
<match my.logs.*>
    @type forest
    subtype gcloud_pubsub
    project xxx
    key xxx.json
    topic ${tag_parts[2]}
</match>
```
but, v0.14 fluentd does not support forest plugin.
so, Could you support tag placeholder for topic ? 
references: https://docs.fluentd.org/v0.14/articles/plugin-update-from-v12
> Use extract_placeholders(template, chunk.metadata) in plugin code.
> Use placeholders ${tag}, ${tag[0]}, ${tag[1]} in configuration.

then, config will be like that.
```
<match my.logs.*>
    @type gcloud_pubsub
    project xxx
    key xxx.json
    topic ${tag[2]}
    <buffer tag>
    </bufefr>
</match>
```

**Comment by mia-0032** [comment]
I'm sorry for my late reply. I think supporting tag placeholder for topic is nice. But I have little time to do it... Please wait for a while.

**Comment by mia-0032** [comment]
I added placeholder feature on v1.1.0. I'll close this issue. Thank you for your request.
