### ISSUE TITLE
attribute_keys option is not working?

### ISSUE THREAD

**Issue by sista05** [mia-0032/fluent-plugin-gcloud-pubsub-custom#67]
The attribute_keys option used for publish is not working because it says record.delete(key).

**Comment by mia-0032** [comment]
@sista05 I'll check if it works later. But I think that `record.delete(key)` returns deleted value. 🤔 
https://docs.ruby-lang.org/ja/latest/method/Hash/i/delete.html

**Comment by sista05** [comment]
Is the purpose of this parameter to remove attributes ?
What if you want to give attributes keys and values? (use fluent-plugin-rewrite-tag-filter?)

**Comment by mia-0032** [comment]
I checked if attribute_keys works with the input and output plugin, but it seems to work fine.

> Is the purpose of this parameter to remove attributes ?

No, this parameter is for giving the value of the record as an attribute.

> What if you want to give attributes keys and values? 

If you want to give a fixed key and value to the attribute, you can do it using the following config.

```
<filter example.publish>
  @type record_transformer
  <record>
    attr1 fixed-value1
    attr2 fixed-value2
  </record>
</filter>
<match example.publish>
  @type gcloud_pubsub
  ...
  attribute_keys attr1,attr2
  ...
</match>
```

**Comment by sista05** [comment]
Oh. I see!!
Thanks @mia-0032!! That would be really great :)
I close this issue.
